project_id = "wuneastyskjxrbsefert"

[functions.create-wordbook-from-pdf]
verify_jwt = false

[functions.generate-word-info]
verify_jwt = false

[functions.save-wordbook]
verify_jwt = false

[functions.change-password]
verify_jwt = false
SBI-A02]유저-목록-조회검색-전공분포-시각화

[functions.delete-user]
verify_jwt = false

develop
